#index:
#    path: /
#    controller: App\Controller\ArticleController::homepage
#api:
#    path: /api
#    controller: App\Controller\TaskController::homepage
#steden:
#    path: /steden
#    controller: App\Controller\CityController::homepage